---
  
- name:   Update APT package cache
  action: apt update_cache=yes
    
- name: Install Java
  apt: pkg={{ item }}
  with_items:
    - openjdk-{{ java_version }}-jre
    - openjdk-{{ java_version }}-jdk
