---
  
# A playbook for installing Datomic free edition 
# 
- name: Install packages
  apt: pkg={{ item }}
  with_items:
    - unzip
    
- name: Create datomic user.
  user: name=datomic state=present

- name: Create datomic data directory
  file: state=directory path={{ datomic_data_dir }} owner=datomic group=datomic

- name: Make datomic log directory
  file: state=directory path=/var/log/datomic owner=datomic group=datomic

- name: Check datomic installation
  command: "ls {{ datomic_dir }}/{{ datomic_filename }}"
  register: datomic_exists
  ignore_errors: true

- name: Create datomic directory
  file: state=directory path={{ datomic_dir }} owner=datomic group=datomic
  when: datomic_exists|failed

- name: Download datomic
  get_url: url=http://downloads.datomic.com/{{ datomic_version}}/{{ datomic_filename }}.zip dest=${datomic_dir}
  when: datomic_exists|failed

- name: Unpack datomic
  command: chdir={{ datomic_dir }} unzip {{ datomic_filename }}.zip
  when: datomic_exists|failed

- name: datomic dir permissions
  shell: chown -R datomic:datomic {{ datomic_dir }}/{{ datomic_filename }}

- name: Upload datomic properties file
  copy: src=datomic-transactor.properties dest={{ datomic_dir }}/transactor.properties

- name: Upload datomic upstart config file
  copy: src=datomic-upstart.conf dest=/etc/init/datomic.conf

- name: Link datomic
  file: src={{ datomic_dir }}/{{ datomic_filename }}
    dest={{ datomic_dir }}/runtime
    owner=datomic
    group=datomic
    state=link
  when: datomic_exists|failed
  
- name: add {{ datomic_path }} to path
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{ datomic_path }}).*?)(["]*)$'
    line="PATH=\1\2:{{ datomic_path }}\3"

- name: ensure datomic is running
  service: name=datomic state=started